url: "https://qriovider.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kazuma Abe's homepage" # the name of your site, e.g. ACME Corp.
description: "Welcome to my website!"
