menu:
- {name: 'about', url: '/about'}
- {name: 'publications', url: '/publications'}
- {name: 'hobbies', url: '/hobbies'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

about:
- {name: 'Primary Investigator', title: 'Graduate student', department: 'Policy & lanning Sciences', institution: 'University of Tsukuba', institution_address: '1-1-1, Tennoudai, Japan', email: 'kazuma.abe8[at].gmail.com', image: 'assets/img/picture3.jpg', url: 'primary-investigator'}

hobbies:
- {name: 'Applied Probability', url: 'applied-probability'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}

social:
- {icon: 'github', link: 'https://github.com/qriovider'}
- {icon: 'twitter', link: 'https://twitter.com/washin27182818'}

contacts:
- {name: 'Kazuma Abe', title: 'Graduate Student', department: '', institution: 'University of Tsukuba', institution_address: '1-1-1, Tennoudai, Japan', email: 'kazuma.abe8[at]gmail.com', image: 'assets/img/picture2.jpg'}
