menu:
- {name: 'About', url: '/about'}
- {name: 'Publications', url: '/publications'}
- {name: 'Hobbies', url: '/hobbies'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

about:
- {name: 'Primary Investigator', title: 'Graduate student', department: 'Policy & Planning Sciences', institution: 'University of Tsukuba', institution_address: '1-1-1, Tennoudai, Japan', email: 'kazuma.abe8[at].gmail.com', image: 'assets/img/picture3.jpg', url: 'primary-investigator'}

hobbies:
- {name: 'Applied Probability', url: 'applied-probability'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Soccer', url: 'soccer'}
- {name: 'Marathon', url: 'marathon'}
- {name: 'Music', url: 'music'}


social:
- {icon: 'github', link: 'https://github.com/qriovider'}
- {icon: 'twitter', link: 'https://twitter.com/washin27182818'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Kazuma-Abe'}

contacts:
- {name: 'Kazuma Abe', title: 'Graduate Student', department: '', institution: 'University of Tsukuba', institution_address: '1-1-1, Tennoudai, Japan', email: 'kazuma.abe8[at]gmail.com', image: 'assets/img/picture2.jpg'}
