menu:
- {name: 'About', url: '/about'}
- {name: 'Publications', url: '/publications'}
- {name: 'CV', url: '/cv'}
- {name: 'Hobbies', url: '/hobbies'}
- {name: 'Contact', url: '/contact'}

about:
- {name: 'Graduate student', title: 'Graduate student', department: 'Policy & Planning Sciences', institution: 'University of Tsukuba', institution_address: '1-1-1, Tennoudai, Japan', email: 'kazuma.abe.spn[at].gmail.com', image: 'assets/img/picture3.jpg', url: 'graduate-student'}

hobbies:
- {name: 'Soccer', url: 'soccer'}
- {name: 'Marathon', url: 'marathon'}
- {name: 'Music', url: 'music'}


social:
- {icon: 'github', link: 'https://github.com/qriovider'}
- {icon: 'twitter', link: 'https://twitter.com/washin27182818'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Kazuma-Abe'}
- {icon: 'spotify', link: 'https://open.spotify.com/user/31ufi47arbp6evtmwjgsg32dm6wm?si=d865d24290d442df'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCGt3q2vulk6Ou191WPBfTLg'}

contacts:
- {name: 'Kazuma Abe', title: 'Graduate student', department: '', institution: 'University of Tsukuba', institution_address: '1-1-1, Tennoudai, Japan', email: 'kazuma.abe.spn[at]gmail.com', image: 'assets/img/picture2.jpg'}
